# Generated by Django 4.1.3 on 2022-12-07 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_breed_dogs_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dogs.breed', verbose_name='Порода'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=50, verbose_name='Дом')),
                ('apartment', models.CharField(max_length=50, verbose_name='Квартира')),
                ('passport_series', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dogs.dogs', verbose_name='Собака')),
            ],
            options={
                'verbose_name': 'Хозяин',
                'verbose_name_plural': 'Хозяева',
                'ordering': ['surname'],
            },
        ),
    ]
